[tool.poetry]
name = "quranbot-aiogram"
version = "0.1.0"
description = ""
authors = ["Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
aiogram = "2.21"
pydantic = {extras = ["dotenv"], version = "1.10.2"}
asyncpg = "0.27.0"
loguru = "0.6.0"
aioredis = "2.0.1"
nats-py = "2.1.7"
quranbot-schema-registry = {git = "https://github.com/blablatdinov/quranbot-schema-registry", branch="master"}
APScheduler = "3.9.1.post1"
databases = "0.6.1"
sentry-sdk = "1.9.9"
SQLAlchemy = "1.4.41"
alembic = "1.8.1"
httpx = "0.23.0"

[tool.poetry.group.dev.dependencies]
wemake-python-styleguide = {git = "https://github.com/wemake-services/wemake-python-styleguide", branch="master"}
ipython = "8.5.0"
mypy = "0.991"
asyncpg-stubs = "0.27.0"
pytest-cov = "4.0.0"
pytest = "7.1.3"
pytest-asyncio = "0.20.0"
mixer = "7.2.2"
black = "22.6.0"
pytest-mock = "3.9.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
skip-string-normalization = true
