[tool.poetry]
name = "quranbot-aiogram"
version = "0.1.0"
description = ""
authors = ["Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.9"
aiogram = "^2.21"
pydantic = {extras = ["dotenv"], version = "^1.9.1"}
asyncpg = "^0.25.0"
loguru = "^0.6.0"
aioredis = "^2.0.1"
nats-py = "^2.1.4"
quranbot-schema-registry = "0.0.3"
APScheduler = "^3.9.1"
databases = {extras = ["asyncpg"], version = "^0.6.0"}

[tool.poetry.dev-dependencies]
wemake-python-styleguide = "^0.16.1"
ipython = "^8.4.0"
mypy = "^0.961"
asyncpg-stubs = "^0.25.4"
Faker = "^13.14.0"
pytest-cov = "^3.0.0"
pytest = "^7.1.2"
pytest-asyncio = "^0.18.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
