[tool.poetry]
name = "quranbot-aiogram"
version = "0.1.0"
description = ""
authors = ["Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>"]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
pydantic = {extras = ["dotenv"], version = "1.10.2"}
asyncpg = "0.27.0"
loguru = "0.6.0"
nats-py = "2.2.0"
quranbot-schema-registry = "0.0.16"
APScheduler = "3.9.1.post1"
databases = "0.6.2"
sentry-sdk = "1.12.0"
SQLAlchemy = "1.4.41"
alembic = "1.9.0"
httpx = "0.23.1"
pytz = "2022.6"
redis = "4.4.0"

[tool.poetry.group.dev.dependencies]
wemake-python-styleguide = {git = "https://github.com/wemake-services/wemake-python-styleguide", branch="master"}
ipython = "8.7.0"
mypy = "0.991"
asyncpg-stubs = "0.27.0"
pytest-cov = "4.0.0"
pytest = "7.2.0"
pytest-asyncio = "0.20.3"
mixer = "7.2.2"
black = "22.12.0"
pytest-mock = "3.10.0"
pytest-lazy-fixture = "0.6.3"
types-pytest-lazy-fixture = "0.6.3.2"
types-pytz = "2022.6.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
skip-string-normalization = true
